number1 = input("Input the 1st number: ")
number2 = input("Input the 2nd number: ")
plus = float(number1) + float(number2)
minus = float(number1) - float(number2)
print(f"{number1} + {number2} = {plus}")
print(f"{number1} - {number2} = {minus}")
